/**
 * SmartForm Mock Data
 *
 * Development-only mock data for testing the SmartForm workflow.
 * This file should NOT be included in production builds.
 *
 * Field names use Oracle convention (UPPER_SNAKE_CASE) to match
 * the production SQL query output format.
 *
 * Oracle date format: 'DD-MMM-YY' (e.g., '15-JAN-25')
 *
 * Usage:
 *   import { generateMockRecords } from '../mocks/smartFormMockData';
 *   const records = generateMockRecords();
 */

import type { SmartFormRecord } from '../types';

/**
 * Generate a mock WEB_LINK for a transaction.
 * Points to the local test-site for development testing.
 * In production, the real Oracle query returns the full PeopleSoft URL.
 */
function mockWebLink(transactionNbr: string): string {
  return `/test-site?TRANSACTION_NBR=${transactionNbr}`;
}

/** Manager approval mock records (MGR_CUR = 1), 15 total */
const MANAGER_RECORDS: SmartFormRecord[] = [
  {
    TRANSACTION_NBR: '123456',
    EMPLID: '800101',
    EMPLOYEE_NAME: 'John Doe',
    NEW_EFFDT: '01-JAN-25',
    CUR_EFFDT: '01-FEB-25',
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123456'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00001',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123457',
    EMPLID: '800102',
    EMPLOYEE_NAME: 'Jane Smith',
    NEW_EFFDT: '15-JAN-25',
    CUR_EFFDT: '15-JAN-25', // Date match scenario
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123457'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00002',
    POSITION_CREATE_CI: 'CI_POSITION_DATA',
    FIELD_DIFFERENCES: '500.00',
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: 'PASS',
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123458',
    EMPLID: '800103',
    EMPLOYEE_NAME: 'Alice Williams',
    NEW_EFFDT: '01-FEB-25',
    CUR_EFFDT: '15-FEB-25',
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123458'),
    EMPL_RCD: 1,
    CUR_POS: 'POS00004',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: 'CI_JOB_DATA',
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123459',
    EMPLID: '800104',
    EMPLOYEE_NAME: 'Bruce Wayne',
    NEW_EFFDT: '20-JAN-25',
    CUR_EFFDT: '01-MAR-25',
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123459'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00006',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: 'CI_POSITION_DATA',
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123460',
    EMPLID: '800105',
    EMPLOYEE_NAME: 'Clark Kent',
    NEW_EFFDT: '10-FEB-25',
    CUR_EFFDT: '10-FEB-25', // Date match scenario
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123460'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00007',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: '1250.00',
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: 'FAIL',
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123461',
    EMPLID: '800106',
    EMPLOYEE_NAME: 'Peter Parker',
    NEW_EFFDT: '05-MAR-25',
    CUR_EFFDT: '01-APR-25',
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123461'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00008',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123462',
    EMPLID: '800107',
    EMPLOYEE_NAME: 'Barry Allen',
    NEW_EFFDT: '08-JAN-25',
    CUR_EFFDT: '08-FEB-25',
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123462'),
    EMPL_RCD: 2,
    CUR_POS: 'POS00020',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123463',
    EMPLID: '800108',
    EMPLOYEE_NAME: 'Hal Jordan',
    NEW_EFFDT: '14-FEB-25',
    CUR_EFFDT: '14-FEB-25', // Date match scenario
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123463'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00021',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: 'PASS',
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123464',
    EMPLID: '800109',
    EMPLOYEE_NAME: 'Arthur Curry',
    NEW_EFFDT: '01-MAR-25',
    CUR_EFFDT: '01-APR-25',
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123464'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00022',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123465',
    EMPLID: '800110',
    EMPLOYEE_NAME: 'Victor Stone',
    NEW_EFFDT: '22-JAN-25',
    CUR_EFFDT: '22-FEB-25',
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123465'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00023',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123466',
    EMPLID: '800111',
    EMPLOYEE_NAME: 'Oliver Queen',
    NEW_EFFDT: '05-FEB-25',
    CUR_EFFDT: '05-MAR-25',
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123466'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00024',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123467',
    EMPLID: '800112',
    EMPLOYEE_NAME: 'Dinah Lance',
    NEW_EFFDT: '10-MAR-25',
    CUR_EFFDT: '10-MAR-25', // Date match scenario
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123467'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00025',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123468',
    EMPLID: '800113',
    EMPLOYEE_NAME: 'Kara Zor-El',
    NEW_EFFDT: '18-JAN-25',
    CUR_EFFDT: '18-FEB-25',
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123468'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00026',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123469',
    EMPLID: '800114',
    EMPLOYEE_NAME: 'John Constantine',
    NEW_EFFDT: '25-FEB-25',
    CUR_EFFDT: '25-MAR-25',
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123469'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00027',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123470',
    EMPLID: '800115',
    EMPLOYEE_NAME: 'Zatanna Zatara',
    NEW_EFFDT: '15-MAR-25',
    CUR_EFFDT: '15-APR-25',
    MGR_CUR: 1,
    WEB_LINK: mockWebLink('123470'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00028',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
];

/** Other approval mock records (MGR_CUR = 0), 25 total */
const OTHER_RECORDS: SmartFormRecord[] = [
  {
    TRANSACTION_NBR: '123471',
    EMPLID: '800201',
    EMPLOYEE_NAME: 'Bob Johnson',
    NEW_EFFDT: '10-JAN-25',
    CUR_EFFDT: '01-MAR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123471'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00003',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123472',
    EMPLID: '800202',
    EMPLOYEE_NAME: 'Charlie Brown',
    NEW_EFFDT: '20-JAN-25',
    CUR_EFFDT: '01-APR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123472'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00005',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123473',
    EMPLID: '800203',
    EMPLOYEE_NAME: 'Diana Prince',
    NEW_EFFDT: '01-MAR-25',
    CUR_EFFDT: '15-MAR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123473'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00003',
    POSITION_CREATE_CI: 'CI_POSITION_DATA',
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123474',
    EMPLID: '800204',
    EMPLOYEE_NAME: 'Tony Stark',
    NEW_EFFDT: '05-JAN-25',
    CUR_EFFDT: '01-FEB-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123474'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00009',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123475',
    EMPLID: '800205',
    EMPLOYEE_NAME: 'Natasha Romanoff',
    NEW_EFFDT: '15-FEB-25',
    CUR_EFFDT: '15-MAR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123475'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00010',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123476',
    EMPLID: '800206',
    EMPLOYEE_NAME: 'Steve Rogers',
    NEW_EFFDT: '25-JAN-25',
    CUR_EFFDT: '25-FEB-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123476'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00011',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123477',
    EMPLID: '800207',
    EMPLOYEE_NAME: 'Wanda Maximoff',
    NEW_EFFDT: '10-MAR-25',
    CUR_EFFDT: '10-APR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123477'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00012',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123478',
    EMPLID: '800208',
    EMPLOYEE_NAME: 'Vision Android',
    NEW_EFFDT: '20-FEB-25',
    CUR_EFFDT: '20-MAR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123478'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00013',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123479',
    EMPLID: '800209',
    EMPLOYEE_NAME: 'Thor Odinson',
    NEW_EFFDT: '30-JAN-25',
    CUR_EFFDT: '28-FEB-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123479'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00014',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123480',
    EMPLID: '800210',
    EMPLOYEE_NAME: 'Loki Laufeyson',
    NEW_EFFDT: '15-MAR-25',
    CUR_EFFDT: '15-APR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123480'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00015',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123481',
    EMPLID: '800211',
    EMPLOYEE_NAME: 'Scott Lang',
    NEW_EFFDT: '05-FEB-25',
    CUR_EFFDT: '05-MAR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123481'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00016',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123482',
    EMPLID: '800212',
    EMPLOYEE_NAME: 'Hope Van Dyne',
    NEW_EFFDT: '12-JAN-25',
    CUR_EFFDT: '12-FEB-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123482'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00017',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123483',
    EMPLID: '800213',
    EMPLOYEE_NAME: 'Stephen Strange',
    NEW_EFFDT: '20-MAR-25',
    CUR_EFFDT: '20-APR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123483'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00018',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123484',
    EMPLID: '800214',
    EMPLOYEE_NAME: 'Carol Danvers',
    NEW_EFFDT: '28-FEB-25',
    CUR_EFFDT: '28-MAR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123484'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00019',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123485',
    EMPLID: '800215',
    EMPLOYEE_NAME: 'James Rhodes',
    NEW_EFFDT: '14-JAN-25',
    CUR_EFFDT: '14-FEB-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123485'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00029',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123486',
    EMPLID: '800216',
    EMPLOYEE_NAME: 'Sam Wilson',
    NEW_EFFDT: '08-FEB-25',
    CUR_EFFDT: '08-FEB-25', // Date match scenario
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123486'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00030',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123487',
    EMPLID: '800217',
    EMPLOYEE_NAME: 'Bucky Barnes',
    NEW_EFFDT: '05-MAR-25',
    CUR_EFFDT: '05-APR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123487'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00031',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123488',
    EMPLID: '800218',
    EMPLOYEE_NAME: 'Clint Barton',
    NEW_EFFDT: '28-JAN-25',
    CUR_EFFDT: '28-FEB-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123488'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00032',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123489',
    EMPLID: '800219',
    EMPLOYEE_NAME: 'Kate Bishop',
    NEW_EFFDT: '18-FEB-25',
    CUR_EFFDT: '18-MAR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123489'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00033',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123490',
    EMPLID: '800220',
    EMPLOYEE_NAME: 'Yelena Belova',
    NEW_EFFDT: '12-MAR-25',
    CUR_EFFDT: '12-APR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123490'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00034',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123491',
    EMPLID: '800221',
    EMPLOYEE_NAME: 'Shuri Wakanda',
    NEW_EFFDT: '06-JAN-25',
    CUR_EFFDT: '06-FEB-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123491'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00035',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123492',
    EMPLID: '800222',
    EMPLOYEE_NAME: 'Okoye General',
    NEW_EFFDT: '22-FEB-25',
    CUR_EFFDT: '22-FEB-25', // Date match scenario
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123492'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00036',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123493',
    EMPLID: '800223',
    EMPLOYEE_NAME: 'Monica Rambeau',
    NEW_EFFDT: '18-MAR-25',
    CUR_EFFDT: '18-APR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123493'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00037',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123494',
    EMPLID: '800224',
    EMPLOYEE_NAME: 'Kamala Khan',
    NEW_EFFDT: '24-JAN-25',
    CUR_EFFDT: '24-FEB-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123494'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00038',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
  {
    TRANSACTION_NBR: '123495',
    EMPLID: '800225',
    EMPLOYEE_NAME: 'America Chavez',
    NEW_EFFDT: '12-FEB-25',
    CUR_EFFDT: '12-MAR-25',
    MGR_CUR: 0,
    WEB_LINK: mockWebLink('123495'),
    EMPL_RCD: 0,
    CUR_POS: 'POS00039',
    POSITION_CREATE_CI: null,
    FIELD_DIFFERENCES: null,
    JOB_UPDATE_CI: null,
    POSITION_UPDATE_CI: null,
    DEPT_CO_UPDATE_CI: null,
    status: 'pending',
  },
];

/**
 * Generate all mock SmartForm records.
 * Returns 15 Manager records (MGR_CUR=1) and 25 Other records (MGR_CUR=0).
 */
export function generateMockRecords(): SmartFormRecord[] {
  return [...MANAGER_RECORDS, ...OTHER_RECORDS];
}

/**
 * Generate only Manager mock records (MGR_CUR=1).
 */
export function generateManagerMockRecords(): SmartFormRecord[] {
  return [...MANAGER_RECORDS];
}

/**
 * Generate only Other mock records (MGR_CUR=0).
 */
export function generateOtherMockRecords(): SmartFormRecord[] {
  return [...OTHER_RECORDS];
}
